services:
  # Aplicación web Flask (sin base de datos externa por ahora)
  - type: web
    name: prestamos-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    # startCommand se maneja a través del Procfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.16
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        value: bastosbarbaranvictor@gmail.com
      - key: MAIL_PASSWORD
        value: ldkhglaolpcofqbs
      - key: LOG_LEVEL
        value: INFO
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
