services:
  # Base de datos PostgreSQL
  - type: postgresql
    name: prestamos-db
    plan: free
    ipAllowList: []
    
  # Aplicación web Flask
  - type: web
    name: prestamos-web
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.16
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: prestamos-db
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        value: bastosbarbaranvictor@gmail.com
      - key: MAIL_PASSWORD
        value: ldkhglaolpcofqbs
      - key: WHATSAPP_API_KEY
        sync: false
      - key: WHATSAPP_PHONE_ID
        sync: false
      - key: LOG_LEVEL
        value: INFO
