services:
  - type: web
    name: sistema-prestamos
    env: python
    plan: free
    buildCommand: pip install -r requirements-lock.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: prestamos-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: prestamos-db
    databaseName: prestamos
    user: prestamos_user
    plan: free
